##
## Build
##
FROM golang:latest as build
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /project-example .

##
## Deploy
##
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /app/project-example /project-example
EXPOSE 8080
CMD ["/project-example"]