##
## Build
##
FROM golang:1.17 AS build
WORKDIR /app
COPY . ./
RUN go mod download
COPY *.go ./
RUN go build -o /project-example

##
## Deploy
##
FROM nginx
WORKDIR /app
COPY --from=build /project-example /project-example
EXPOSE 8000
ENTRYPOINT ["/project-example"]